name: Sync Schedule by tag

on:
  push:
    branches:
      - main

jobs:
  sync-latest-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/phennapa/github-actions-demo01.git
        git fetch upstream

    - name: Fetch latest upstream versions, then merge to 'main'
      run: |
        SYNC_VERSION=$(curl --write-out '%{redirect_url}' 'https://github.com/phennapa/github-actions-demo01/releases/latest' | sed 's,.*/v/,')
        echo "new version $SYNC_VERSION"
        git checkout -b new-tag-$SYNC_VERSION
        git merge --allow-unrelated-histories upstream/main
        git push origin new-tag-$SYNC_VERSION

    - name: Push to remote origin
      run: |
        git push origin new-tag-$SYNC_VERSION
