name: Sync Schedule by tag

on:
  push:
    branches:
      - main

jobs:
  sync-latest-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/phennapa/github-actions-demo01.git
        git fetch upstream

    - name: Fetch latest upstream versions, then merge to 'main'
      run: |
        SYNC_VERSION="v$(curl --write-out '%{redirect_url}' 'https://github.com/phennapa/github-actions-demo01/releases/latest' | sed 's,.*/v,,')"
        echo "new version $SYNC_VERSION"
        git checkout -b new-tag-$SYNC_VERSION
        git merge --allow-unrelated-histories upstream/main || true
        if [ -n "$(git ls-files --unmerged)" ]; then
          echo "Resolving merge conflicts..."
          # Automatically choose the upstream version for conflicting files
          git checkout --theirs .
          git add .
          git commit -m "Resolved merge conflicts"
        fi

    - name: Push to remote origin
      run: |
        git push origin new-tag-$SYNC_VERSION
